run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/hashicorp/terraform-provider-taskmate
